
"attribute" = { fg = "base4" }
"comment" = { fg = "base3", modifiers = ["italic"] }
"comment.line" = {}
"comment.block" = {}
"comment.block.documentation" = { fg = "base2" }
"constant" = { fg = "base1", modifiers = ["bold"] }
"constructor" = { fg = "base1" }
"function" = { fg = "base1", modifiers = ["bold"] }
"keyword" = { fg = "base1" }
"label" = { modifiers = ["bold"] }
"namespace" = { fg = "base1" }
"operator" = { fg = "base1" }
"punctuation.bracket" = { modifiers = ["bold"] }
"special" = { fg = "base1" }
"string" = { fg = "base5" }
"type" = { fg = "base4" }
"variable" = { fg = "base4" }
"variable.parameter" = { fg = "base4" }

"diagnostic" = { modifiers = ["underlined"] }

"diagnostic.info" = { underline = { color = "diff_change", style = "curl" } }
"diagnostic.warning" = { underline = { color = "diff_change", style = "curl" } }
"diagnostic.error" = { underline = { color = "diff_delete", style = "curl" } }

"info" = { fg = "diff_change" }
"hint" = { modifiers = ["bold"] }
"warning" = { fg = "diff_change" }
"error" = { fg = "diff_delete" }

"markup.heading" = { fg = "purple_bg", modifiers = [
  "bold",
] }
"markup.raw" = { fg = "base5" }
"markup.raw.inline" = { fg = "base5" }
"markup.raw.block" = { fg = "base5" }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "blue_bg", modifiers = [
  "underlined",
] }
"markup.link.label" = { fg = "link" }
"markup.link.text" = { fg = "link" }
"markup.quote" = { fg = "base5" }
"markup.list" = { fg = "base5" }

"ui.background" = { fg = "base1", bg = "base7" }
"ui.cursorline" = { bg = "base6" }
"ui.cursor" = { fg = "base1", bg = "base7", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base1", bg = "base7", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "base5", bg = "base3", modifiers = ["reversed"] }
"ui.selection" = { bg = "base6" }
"ui.selection.primary" = { bg = "base5", fg = "base7" }
"ui.highlight" = { bg = "base6", modifiers = ["bold"] }

"ui.virtual" = { fg = "base5" }
"ui.virtual.whitespace" = { fg = "base5" }
"ui.virtual.ruler" = { bg = "base6" }
"ui.virtual.inlay-hint" = { fg = "base4", modifiers = ["normal"] }
"ui.virtual.inlay-hint.parameter" = { fg = "base3", modifiers = ["normal"] }
"ui.virtual.inlay-hint.type" = { fg = "base3", modifiers = ["italic"] }

"ui.linenr" = { bg = "base7" }
"ui.linenr.selected" = { fg = "base5"}

"ui.statusline" = { fg = "base7", bg = "base1", modifiers = ["bold"] }
"ui.statusline.inactive" = { fg = "base5", bg = "base1", modifiers = ["italic"] }

"ui.text" = { fg = "base1" }
"ui.text.focus" = { fg = "base1", modifiers = ["bold"] }

"ui.menu" = { fg = "base1", bg = "base7" }
"ui.menu.selected" = { fg = "base1", bg = "base6", modifiers = ["reversed"] }
"ui.menu.scroll" = { fg = "base1", bg = "base6" }
"ui.help" = { fg = "base1", bg = "base6" }
"ui.popup" = { fg = "base1", bg = "base6" }
"ui.window" = { fg = "base1", bg = "base6" }

"diff.plus" = { fg = "diff_add" }
"diff.delta" = { fg = "diff_change" }
"diff.minus" = { fg = "diff_delete" }

[palette]
base7 = "#48443E"
base6 = "#6B5F4D"
base5 = "#b9a992"
base4 = "#dcd3c6"
base3 = "#e4ddd2"
base2 = "#f1ece4"
base1 = "#f7f3ee"

accent = "#f1ddf1"
link = "#8DB5DD"
diff_add = "#7FCE8F"
diff_change = "#E5BF74"
diff_delete = "#D77676"
diff_renamed = "#52aeff"
